---
# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 0.4.0
_src_path: gh:radio-aktywne/template-app-generic
accountname: radio-aktywne
appname: emiarchive
description: Emission archive 🗃️
docs: true
docsurl: https://radio-aktywne.github.io/app-emiarchive
envprefix: EMIARCHIVE
imagename: apps/emiarchive
registry: true
releases: true
reponame: app-emiarchive
repourl: https://github.com/radio-aktywne/app-emiarchive
