# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 0.5.0
_src_path: gh:radio-aktywne/template-database-minio
accountname: radio-aktywne
databasename: emerald
description: Broadcast recordings media 📼
docs: true
docsurl: https://radio-aktywne.github.io/emerald
envprefix: EMERALD
imagename: databases/emerald
port: 30000
registry: true
releases: true
reponame: emerald
repourl: https://github.com/radio-aktywne/emerald
webport: 30001
