# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 0.2.0
_src_path: gh:radio-aktywne/template-database-minio
accountname: radio-aktywne
databasename: emiarchive
description: Emission archive 🗃️
docs: true
docsurl: https://radio-aktywne.github.io/database-emiarchive
envprefix: EMIARCHIVE
imagename: databases/emiarchive
port: 30000
registry: true
releases: true
reponame: database-emiarchive
repourl: https://github.com/radio-aktywne/database-emiarchive
webport: 30001
