services:
  emerald:
    build:
      context: ./
      network: host
    environment:
      - "EMERALD__SERVER__HOST=${EMERALD__SERVER__HOST:-0.0.0.0}"
      - "EMERALD__SERVER__PORTS__S3=${EMERALD__SERVER__PORTS__S3:-10710}"
      - "EMERALD__SERVER__PORTS__WEB=${EMERALD__SERVER__PORTS__WEB:-10711}"
      - "EMERALD__URLS__WEB=${EMERALD__URLS__WEB:-http://localhost:10711}"
      - "EMERALD__CREDENTIALS__ADMIN__USER=${EMERALD__CREDENTIALS__ADMIN__USER:-admin}"
      - "EMERALD__CREDENTIALS__ADMIN__PASSWORD=${EMERALD__CREDENTIALS__ADMIN__PASSWORD:-password}"
      - "EMERALD__CREDENTIALS__READONLY__USER=${EMERALD__CREDENTIALS__READONLY__USER:-readonly}"
      - "EMERALD__CREDENTIALS__READONLY__PASSWORD=${EMERALD__CREDENTIALS__READONLY__PASSWORD:-password}"
      - "EMERALD__CREDENTIALS__READWRITE__USER=${EMERALD__CREDENTIALS__READWRITE__USER:-readwrite}"
      - "EMERALD__CREDENTIALS__READWRITE__PASSWORD=${EMERALD__CREDENTIALS__READWRITE__PASSWORD:-password}"
    network_mode: host
    volumes:
      - data:/database/data/

volumes:
  data: {}
