services:
  mediarecords:
    build:
      context: ./
      network: host
    environment:
      - "MEDIARECORDS__SERVER__HOST=${MEDIARECORDS__SERVER__HOST:-0.0.0.0}"
      - "MEDIARECORDS__SERVER__PORTS__S3=${MEDIARECORDS__SERVER__PORTS__S3:-30000}"
      - "MEDIARECORDS__SERVER__PORTS__WEB=${MEDIARECORDS__SERVER__PORTS__WEB:-30001}"
      - "MEDIARECORDS__URLS__WEB=${MEDIARECORDS__URLS__WEB:-http://localhost:30001}"
      - "MEDIARECORDS__CREDENTIALS__ADMIN__USER=${MEDIARECORDS__CREDENTIALS__ADMIN__USER:-admin}"
      - "MEDIARECORDS__CREDENTIALS__ADMIN__PASSWORD=${MEDIARECORDS__CREDENTIALS__ADMIN__PASSWORD:-password}"
      - "MEDIARECORDS__CREDENTIALS__READONLY__USER=${MEDIARECORDS__CREDENTIALS__READONLY__USER:-readonly}"
      - "MEDIARECORDS__CREDENTIALS__READONLY__PASSWORD=${MEDIARECORDS__CREDENTIALS__READONLY__PASSWORD:-password}"
      - "MEDIARECORDS__CREDENTIALS__READWRITE__USER=${MEDIARECORDS__CREDENTIALS__READWRITE__USER:-readwrite}"
      - "MEDIARECORDS__CREDENTIALS__READWRITE__PASSWORD=${MEDIARECORDS__CREDENTIALS__READWRITE__PASSWORD:-password}"
    network_mode: host
    volumes:
      - data:/database/data/

volumes:
  data: {}
