---
services:
  emiarchive:
    build: .
    network_mode: host
    environment:
      - "EMIARCHIVE_PORT=${EMIARCHIVE_PORT:-30000}"
      - "EMIARCHIVE_ADMIN_PORT=${EMIARCHIVE_ADMIN_PORT:-30001}"
      - "EMIARCHIVE_ADMIN_PUBLIC_URL=${EMIARCHIVE_ADMIN_PUBLIC_URL:-http://localhost:30001}"
      - "EMIARCHIVE_ADMIN_USER=${EMIARCHIVE_ADMIN_USER:-admin}"
      - "EMIARCHIVE_ADMIN_PASSWORD=${EMIARCHIVE_ADMIN_PASSWORD:-password}"
      - "EMIARCHIVE_READONLY_USER=${EMIARCHIVE_READONLY_USER:-readonly}"
      - "EMIARCHIVE_READONLY_PASSWORD=${EMIARCHIVE_READONLY_PASSWORD:-password}"
      - "EMIARCHIVE_READWRITE_USER=${EMIARCHIVE_READWRITE_USER:-readwrite}"
      - "EMIARCHIVE_READWRITE_PASSWORD=${EMIARCHIVE_READWRITE_PASSWORD:-password}"
      - "EMIARCHIVE_LIVE_BUCKET=${EMIARCHIVE_LIVE_BUCKET:-live}"
      - "EMIARCHIVE_PRERECORDED_BUCKET=${EMIARCHIVE_PRERECORDED_BUCKET:-prerecorded}"
    volumes:
      - data:/app/data

volumes:
  data: {}
