services:
  emiarchive:
    build:
      context: ./
      network: host
    environment:
      - "EMIARCHIVE__SERVER__HOST=${EMIARCHIVE__SERVER__HOST:-0.0.0.0}"
      - "EMIARCHIVE__SERVER__PORTS__S3=${EMIARCHIVE__SERVER__PORTS__S3:-30000}"
      - "EMIARCHIVE__SERVER__PORTS__WEB=${EMIARCHIVE__SERVER__PORTS__WEB:-30001}"
      - "EMIARCHIVE__URLS__WEB=${EMIARCHIVE__URLS__WEB:-http://localhost:30001}"
      - "EMIARCHIVE__CREDENTIALS__ADMIN__USER=${EMIARCHIVE__CREDENTIALS__ADMIN__USER:-admin}"
      - "EMIARCHIVE__CREDENTIALS__ADMIN__PASSWORD=${EMIARCHIVE__CREDENTIALS__ADMIN__PASSWORD:-password}"
      - "EMIARCHIVE__CREDENTIALS__READONLY__USER=${EMIARCHIVE__CREDENTIALS__READONLY__USER:-readonly}"
      - "EMIARCHIVE__CREDENTIALS__READONLY__PASSWORD=${EMIARCHIVE__CREDENTIALS__READONLY__PASSWORD:-password}"
      - "EMIARCHIVE__CREDENTIALS__READWRITE__USER=${EMIARCHIVE__CREDENTIALS__READWRITE__USER:-readwrite}"
      - "EMIARCHIVE__CREDENTIALS__READWRITE__PASSWORD=${EMIARCHIVE__CREDENTIALS__READWRITE__PASSWORD:-password}"
      - "EMIARCHIVE__BUCKETS__LIVE=${EMIARCHIVE__BUCKETS__LIVE:-live}"
      - "EMIARCHIVE__BUCKETS__PRERECORDED=${EMIARCHIVE__BUCKETS__PRERECORDED:-prerecorded}"
    network_mode: host
    volumes:
      - data:/database/data/

volumes:
  data: {}
