services:
  datarecords:
    build:
      context: ./
      network: host
    environment:
      - "DATARECORDS__SERVER__HOST=${DATARECORDS__SERVER__HOST:-0.0.0.0}"
      - "DATARECORDS__SERVER__PORTS__S3=${DATARECORDS__SERVER__PORTS__S3:-30000}"
      - "DATARECORDS__SERVER__PORTS__WEB=${DATARECORDS__SERVER__PORTS__WEB:-30001}"
      - "DATARECORDS__URLS__WEB=${DATARECORDS__URLS__WEB:-http://localhost:30001}"
      - "DATARECORDS__CREDENTIALS__ADMIN__USER=${DATARECORDS__CREDENTIALS__ADMIN__USER:-admin}"
      - "DATARECORDS__CREDENTIALS__ADMIN__PASSWORD=${DATARECORDS__CREDENTIALS__ADMIN__PASSWORD:-password}"
      - "DATARECORDS__CREDENTIALS__READONLY__USER=${DATARECORDS__CREDENTIALS__READONLY__USER:-readonly}"
      - "DATARECORDS__CREDENTIALS__READONLY__PASSWORD=${DATARECORDS__CREDENTIALS__READONLY__PASSWORD:-password}"
      - "DATARECORDS__CREDENTIALS__READWRITE__USER=${DATARECORDS__CREDENTIALS__READWRITE__USER:-readwrite}"
      - "DATARECORDS__CREDENTIALS__READWRITE__PASSWORD=${DATARECORDS__CREDENTIALS__READWRITE__PASSWORD:-password}"
      - "DATARECORDS__BUCKETS__LIVE=${DATARECORDS__BUCKETS__LIVE:-live}"
      - "DATARECORDS__BUCKETS__PRERECORDED=${DATARECORDS__BUCKETS__PRERECORDED:-prerecorded}"
    network_mode: host
    volumes:
      - data:/database/data/

volumes:
  data: {}
